### PR TITLE
Python 3 and pep 8 fixes

### PR DESCRIPTION
**Pull request by Pansanel**
This PR contains several changes:
* Pep 8 syntax fixes
* Some code fixes for Python3 compliance
* Several comments have been updated (pydocstyle recommendations)

### CODE REVIEW

**Comment by Pansanel** [comment]
Ubuntu packages have been successfully built using this modifications (with Python 3). The debian build files are available on GitHub:
https://github.com/Pansanel/linux-packaging
The Ubuntu packages are available on this ppa:
https://launchpad.net/~pansanel/+archive/ubuntu/gfal2

**Comment by andrea-manzi** [comment]
Hello,
thanks a lot for your PR
the current gfal2 maintainer was not in the github group so it didn't get the notifications, i just added him and i will let him know about your contribution 
cheers
Andrea

**Comment by andrea-manzi** [comment]
ciao @okeeble @EdwardKaravakis , could you please check this PR or pass it to Michal?

**Comment by EdwardKaravakis** [comment]
thanks @andrea-manzi , I will pass it to Michal.

**Comment by mpatrascoiu** [comment]
Hello,

We've updated our codebase to Python 2/3 compatible code.
If still of actuality, would you care reviewing this pull request?

Cheers,
Mihai

**Comment by mpatrascoiu** [comment]
Hello,

Our code has been Python3 compliant since quite some time.
Nowadays, the proposed merge request has to be revised.

I believe it would only bring in the PEP 8 fixes.
If that's the case, it's better to start a new merge request against the current `develop` branch.

Cheers,
Mihai

**Pull request closed without merging**
